import { Inter } from "next/font/google";

import ClientLayout from "./ClientLayout";
import { getUserSession } from "./actions/getUserSession";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: any }) {
  const session = await getUserSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout session={session!}>{children}</ClientLayout>
      </body>
    </html>
  );
}
